## Intro to NumPy 
NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays (https://en.wikipedia.org/wiki/NumPy).

Numpy is incredibly fast, as it has bindings to C libraries. 

In [1]:
import numpy as np

## Creation of NumPy array
### From a list

In [2]:
a_list = [1, 2, 3]
a_array = np.array(a_list)

In [3]:
print(type(a_list))
print(type(a_array))

<class 'list'>
<class 'numpy.ndarray'>


In [4]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
a_2D = np.array(matrix)

### Using built-in methods

In [5]:
np.arange(0, 10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0, 10, 2) # np.arange(start, stop, step)

array([0, 2, 4, 6, 8])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.linspace(0, 10, 20) # np.linspace(start, stop, num=50) 

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## Random 

### uniform
Return an array of the given shape with random samples from a uniform distribution

In [10]:
np.random.uniform(0, 1, 5) # (low, high, size)

array([0.3675849 , 0.82960256, 0.3899072 , 0.66498084, 0.88701789])

### randn
Return samples from the “standard normal” distribution.

In [11]:
np.random.randn(2,2) # standard normal (Gaussian) distribution of mean 0 and variance 1

array([[ 0.6074728 ,  1.38917217],
       [-0.43151165, -0.46698356]])

### normal

In [12]:
mu, sigma = 1, 0.5 # mean and standard deviation
np.random.normal(mu, sigma, size = (3, 2))

array([[-0.1806302 ,  1.03502898],
       [ 1.13974216,  0.9653996 ],
       [ 1.57688391,  1.17667748]])

### multivariate normal

In [13]:
mean = [1, 2]
cov = [[1, 0], [0, 1]]
np.random.multivariate_normal(mean, cov, size= (3, 2))

array([[[ 1.73854145,  1.56040711],
        [-0.04410092,  1.18791045]],

       [[ 1.89851206,  0.40482798],
        [ 0.98788867,  3.0082401 ]],

       [[ 0.2774077 ,  1.01417244],
        [ 2.35739562,  0.75555025]]])

### randint
Return random integers 

In [14]:
np.random.randint(1, 100, 5) # randint(low, high=None, size=None)

array([32, 10, 51, 96,  2])

### seed()
The seed() method is used to initialize the random number generator.

In [15]:
np.random.seed(0)  

### Operations

In [16]:
arr = np.arange(0, 10) 
arr_r = arr.reshape(2, 5)
print('arr: ')
print(arr)
print('arr_r: ')
print(arr_r)

arr: 
[0 1 2 3 4 5 6 7 8 9]
arr_r: 
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [17]:
my_arr = np.random.randint(1, 100, 10)
print(my_arr)

[45 48 65 68 68 10 84 22 37 88]


In [18]:
my_arr.max()

np.int64(88)

In [19]:
my_arr.argmax()

np.int64(9)

In [20]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

In [21]:
arr_1 + arr_2

array([5, 7, 9])

In [22]:
arr_1 * arr_2

array([ 4, 10, 18])

In [23]:
np.exp(arr_1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [24]:
np.log(arr_1)

array([0.        , 0.69314718, 1.09861229])